volumes:
  pg_data:

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: plakar
    ports:
      - "7432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./postgres/init-barman.sh:/docker-entrypoint-initdb.d/init-barman.sh:ro
      - ./postgres/postgresql.conf:/etc/plakar/postgresql.conf:ro
      - ./postgres/pg_hba.conf:/etc/plakar/pg_hba.conf:ro
    command:
      - "postgres"
      - "-c"
      - "config_file=/etc/plakar/postgresql.conf"
      - "-c"
      - "hba_file=/etc/plakar/pg_hba.conf"

  barman:
    build: ./barman
    volumes:
      - ./barman/barman.conf:/etc/barman.d/barman.conf:ro
      - ./barman/pgpass:/var/lib/barman/.pgpass:ro
      - ./barman/entrypoint.sh:/entrypoint.sh:ro
      - ./barman/lego.sql:/var/data/lego.sql:ro
    entrypoint:
      - /entrypoint.sh
    command:
      - sleep
      - infinity
